/**
 * Proves the TypeScript numerics twin agrees with the Python core (PLAN.md
 * section 6.4). Fixtures are generated by scripts/gen_fixtures.py -- rerun
 * that script after changing any Python model/solver/reference arithmetic,
 * and this test will catch a divergence in CI.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import { MODEL_REGISTRY } from "../src/numerics/models";
import { integrate, type SolverName } from "../src/numerics/solvers";
import { SIRReference } from "../src/numerics/reference";

const here = path.dirname(fileURLToPath(import.meta.url));
const solverCases = JSON.parse(readFileSync(path.join(here, "fixtures/solver_cases.json"), "utf-8"));
const referenceCase = JSON.parse(readFileSync(path.join(here, "fixtures/reference_case.json"), "utf-8"));

function maxAbsDiff(a: number[][], b: number[][]): number {
  let m = 0;
  for (let i = 0; i < a.length; i++) {
    for (let j = 0; j < a[i].length; j++) {
      m = Math.max(m, Math.abs(a[i][j] - b[i][j]));
    }
  }
  return m;
}

describe("solver parity: TypeScript vs Python", () => {
  for (const c of solverCases) {
    it(`${c.model} / ${c.solver} / h=${c.h}`, () => {
      const ModelClass = (MODEL_REGISTRY as any)[c.model];
      const model = new ModelClass(c.n_total);
      const result = integrate(model, c.y0, c.theta, 0.0, c.t_final, c.solver as SolverName, c.h);
      expect(result.t.length).toBe(c.t.length);
      const diff = maxAbsDiff(result.y, c.y);
      // solver states are O(1) to O(1e3); 1e-9 absolute is comfortably
      // tighter than any accuracy claim this project makes about a solver.
      expect(diff).toBeLessThan(1e-9);
    });
  }
});

describe("reference (gold standard) parity: TypeScript vs Python", () => {
  it("trajectory matches at every t_eval point", () => {
    const ref = new SIRReference({
      beta: referenceCase.beta,
      gamma: referenceCase.gamma,
      nTotal: referenceCase.n_total,
      s0: referenceCase.s0,
      i0: referenceCase.i0,
    });
    let maxDiff = 0;
    referenceCase.t_eval.forEach((t: number, idx: number) => {
      const { s, i, r } = ref.trajectoryAt(t);
      const [sTrue, iTrue, rTrue] = referenceCase.trajectory[idx];
      maxDiff = Math.max(maxDiff, Math.abs(s - sTrue), Math.abs(i - iTrue), Math.abs(r - rTrue));
    });
    expect(maxDiff).toBeLessThan(1e-6);
  });

  it("peak_i, peak_time, s_infinity match", () => {
    const ref = new SIRReference({
      beta: referenceCase.beta,
      gamma: referenceCase.gamma,
      nTotal: referenceCase.n_total,
      s0: referenceCase.s0,
      i0: referenceCase.i0,
    });
    expect(Math.abs(ref.peakI - referenceCase.peak_i)).toBeLessThan(1e-6);
    expect(Math.abs(ref.peakTime() - referenceCase.peak_time)).toBeLessThan(1e-6);
    expect(Math.abs(ref.sInfinity - referenceCase.s_infinity)).toBeLessThan(1e-6);
  });
});
